# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-20 23:02
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.CharField(max_length=50)),
                ('external_id', models.CharField(max_length=100)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(default=uuid.uuid4, max_length=32)),
                ('type_id', models.CharField(max_length=30)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='resource',
            unique_together=set([('type_id', 'identifier')]),
        ),
        migrations.AddField(
            model_name='applicationresource',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unite.Resource'),
        ),
        migrations.AlterUniqueTogether(
            name='applicationresource',
            unique_together=set([('resource', 'app_id')]),
        ),
    ]
