# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-19 23:25
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(default=uuid.uuid4, max_length=32)),
                ('type_id', models.CharField(max_length=30)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='resource',
            unique_together=set([('type_id', 'identifier')]),
        ),
    ]
