# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-21 00:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unite', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='applicationresource',
            unique_together=set([('resource', 'app_id', 'external_id')]),
        ),
    ]
